### ISSUE TITLE
Update jBCrypt dep to 0.4

### ISSUE THREAD

**Issue by fosskers** [t3hnar/scala-bcrypt#10]
jBCrypt was updated in January, after five years.

**Comment by t3hnar** [comment]
I found updated dependency `"de.svenkubiak" % "jBCrypt" % "0.4"` and it is compiled against Java 1.8, I don't want to add requirement of java 1.8 for this lib...

**Comment by fosskers** [comment]
That's makes sense. Maybe wait a year? It might be good to know specifically what changed between 0.3 and 0.4.

**Comment by t3hnar** [comment]
Here are [release notes](http://www.mindrot.org/projects/jBCrypt/news/rel04.html)
*This corrects an integer overflow that occurs with very large log_rounds values, first reported by Marcus Rathsfeld*

**Comment by fosskers** [comment]
If that's all, then not upgrading might not be the end of the world. `log_rounds` is typically 10, yeah?

**Comment by fosskers** [comment]
Would you considering this now, given that Play 2.4 requires Java 8?

**Comment by t3hnar** [comment]
yep, let's give it a try.

**Comment by fosskers** [comment]
The lib isn't coming from `org.mindrot` anymore?

**Comment by t3hnar** [comment]
Yes, and it never comes compatible with java 1.8

**Comment by fosskers** [comment]
What do you mean?

**Comment by t3hnar** [comment]
@fosskers there is no `org.mindrot` in published to maven of v0.4

**Comment by fosskers** [comment]
But 0.4 is java 8 compatible?

**Comment by t3hnar** [comment]
@fosskers  Yes

**Comment by fosskers** [comment]
Ok thanks
