### ISSUE TITLE
object github is not a member of package com

### ISSUE THREAD

**Issue by mkovacek** [t3hnar/scala-bcrypt#13]
When I import  **_import com.github.t3hnar.bcrypt.__**  I receive compilation error "object github is not a member of package com"

I'm using Playframework 2.5.4 , SBT

**Comment by flurdy** [comment]
Have you added it to your dependencies?

     libraryDependencies += "com.github.t3hnar" %% "scala-bcrypt" % "2.6"

**Comment by mkovacek** [comment]
Everything is ok now, I needed to stop and run app again.
