### ISSUE TITLE
Publish for Scala v2.12.0

### ISSUE THREAD

**Issue by marconilanna** [t3hnar/scala-bcrypt#15]
The [Scala 2.12.0 release train](https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md) is here. Please publish for 2.12.0 and [submit a pull request](https://github.com/scala/make-release-notes/edit/2.12.x/projects-2.12.md) to let the world know what libraries are available.

**Comment by calvinlfer** [comment]
This has been completed :-)
